### ISSUE TITLE
gather embeddings for used node

### ISSUE THREAD

**Issue by linyaoyang** [MaoXinn/PSR#2]
Hi, I am wondering why you need to gather the embeddings first before it is used in the subsequent module, as in the code:

ent_emb = Lambda(lambda x: K.squeeze(K.gather(indices=K.cast(x[0], "int32"), reference=x[1]), axis=0))([used_node, ent_emb])

as in the following you gather corresponding ent_engt embeddings when aggregating information. However, if i remove this line, the performance of this model drops dramatically. It confused me a lot.

**Comment by MaoXinn** [comment]
因为psr每个batch处理的不是完整的图谱，而是一个采样后的子图。
这行代码的目的是取出当前子图所需要的实体embedding（也就是used_node）。
